# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f03be373d896c82e60c828dce9c8d845df71f0e843d9edec8e02a1143b167e8279bb2b725cea4ae53197c3e4873ddc6fad05cb7feb817c2b5a7fb4011e366c6

test:
  secret_key_base: f6865613f39e37a8b21f4c9c6227f5b1c1c3787d4c8bb9387b2e26636411da843bd6078a57a33e00561f47a7e32db84671b6ceb681938f0d03f4ffb1fc30e901

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
